# NumPy

In [2]:
import numpy as np

### 1. Create an array containing the numbers from 1 to 10

In [3]:
array_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

### 2. Print the array

In [4]:
print(array_1)

[ 1  2  3  4  5  6  7  8  9 10]


### 3. Display its maximum and minimum values.

In [5]:
print("Min: ", np.min(array_1))
print("Max: ", np.max(array_1))

Min:  1
Max:  10


### 4. Create an array of 5 zeros

In [ ]:
array_2 = np.array([0, 0, 0, 0, 0])
print(array_2)

### 5. Create an array of 5 ones.

In [ ]:
array_3 = np.array([1, 1, 1, 1, 1])
print(array_3)

### 6. Create a matrix

In [7]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

### 7. Display the matrix

In [8]:
print(matrix)

[[1 2 3]
 [4 5 6]]


### 8. Use .shape to display its dimensions.

In [9]:
matrix.shape

(2, 3)